# -*- python -*-
Import("env")

env.Append(LIBS=['mpich'])

# Build Pipeline
env.Object(['Pipeline.cc', 'Clipboard.cc', 'Stage.cc', 'Queue.cc'])

# Build Slice
env.Object(['Slice.cc', 'Clipboard.cc', 'Stage.cc', 'Queue.cc'])

